# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0014_auto_20180107_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='compony',
            field=models.ManyToManyField(null=True, related_name='compony', to=settings.AUTH_USER_MODEL),
        ),
    ]
